TrajectoryPlannerROS:
  max_vel_x: 0.6
  min_vel_x: -0.6
  max_vel_theta: 8.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 10
  acc_lim_x: 8
  acc_lim_y: 0
  
  meter_scoring: true
  holonomic_robot: false