TrajectoryPlannerROS:
  # Velocity Config
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_vel_theta: 2.0
  min_vel_theta: -2.0
  # Acceleration Config
  acc_lim_theta: 2
  acc_lim_x: 1
  acc_lim_y: 0
  # Goal Tolerance
  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.01
  latch_xy_goal_tolerance: false
  #
  meter_scoring: true
  #Robot Config
  holonomic_robot: false