local_costmap:
  global_frame: /amanita_cecilia_pc/odom
  robot_base_frame: /amanita_cecilia_pc/base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05